import { BRAND } from "@/lib/brand";

/**
 * Every page's metadata, assembled in one place.
 *
 * ## Why a helper rather than a literal per route
 *
 * A complete head is eleven tags. Written out per route they drift: one page
 * gets a Twitter card and another does not, a title is updated in `<title>` and
 * not in `og:title`, and the card a link produces stops matching the page it
 * points at. Here a route names a title, a description and its path, and the
 * eleven follow.
 *
 * ## The image
 *
 * One card for the whole site rather than one per page. Per-page cards are
 * better when the page *is* the content — a blog, a profile — and this is a
 * marketing site plus a console behind a sign-in, where every shareable page
 * says the same thing about the same product. A second card would be two files
 * to keep current for no gain.
 *
 * `public/og.png` is generated by `scripts/build-og-image.mjs` from the logo, so
 * it cannot fall behind a rebrand.
 */

/**
 * Where this is deployed.
 *
 * Open Graph requires absolute URLs — a crawler has no page context to resolve
 * a relative one against, and every platform silently drops the image rather
 * than guessing. So this constant is what makes the cards work at all, and it
 * has to match the domain the site is actually served from.
 */
export const SITE_URL = "https://startersaaskit.com";

/** 1200x630, the size every platform crops from. */
export const OG_IMAGE_PATH = "/og.png";
export const OG_IMAGE_SIZE = { width: 1200, height: 630 };

/** What a page says about itself before any route overrides it. */
export const DEFAULT_DESCRIPTION =
	"Answer a few questions — framework, components, database, ORM, auth, billing, email — and download a repository with all of it wired together and its test suite already green.";

export type Meta = Record<string, string>;

/** Absolute, and without a doubled slash when the path is "/". */
export function absolute(path: string): string {
	return path === "/" ? SITE_URL : `${SITE_URL}${path}`;
}

/**
 * The `<title>`, which is not the same string as the heading.
 *
 * A tab and a search result both truncate, and both show the beginning, so the
 * distinguishing word goes first and the brand last. The home page is the one
 * exception: "StarterSaaSKit · StarterSaaSKit" helps nobody.
 */
export function titleFor(title?: string): string {
	return title ? `${title} · ${BRAND}` : BRAND;
}

/**
 * A page's head: title, description, canonical, Open Graph and Twitter.
 *
 * `noIndex` is not decoration. Everything behind the sign-in is either an empty
 * shell to a crawler or somebody's private console, and neither belongs in a
 * search index — so console routes pass it and marketing routes do not.
 */
export function pageHead({
	description = DEFAULT_DESCRIPTION,
	noIndex = false,
	path,
	title,
}: {
	description?: string;
	noIndex?: boolean;
	path: string;
	title?: string;
}): { meta: Meta[]; links: Meta[] } {
	const full = titleFor(title);
	const url = absolute(path);
	const image = `${SITE_URL}${OG_IMAGE_PATH}`;

	const meta: Meta[] = [
		{ title: full },
		{ name: "description", content: description },

		{ property: "og:type", content: "website" },
		{ property: "og:site_name", content: BRAND },
		{ property: "og:title", content: full },
		{ property: "og:description", content: description },
		{ property: "og:url", content: url },
		{ property: "og:image", content: image },
		{ property: "og:image:width", content: String(OG_IMAGE_SIZE.width) },
		{ property: "og:image:height", content: String(OG_IMAGE_SIZE.height) },
		/* Read aloud by screen readers when a card is focused, and the one part
		   of a preview a blind reader gets. */
		{ property: "og:image:alt", content: `${BRAND} — ${description}` },

		/* `summary_large_image`, not `summary`: the small card crops a 1200x630
		   image to a square and cuts the wordmark in half. */
		{ name: "twitter:card", content: "summary_large_image" },
		{ name: "twitter:title", content: full },
		{ name: "twitter:description", content: description },
		{ name: "twitter:image", content: image },
	];

	if (noIndex) {
		/* `follow` as well as `noindex`: the page should not be listed, but the
		   links out of it are still worth crawling. */
		meta.push({ name: "robots", content: "noindex, follow" });
	}

	return {
		meta,
		/* Canonical even on pages with no query string, because a page reached
		   with a tracking parameter is otherwise a second URL with the same
		   content. */
		links: [{ rel: "canonical", href: url }],
	};
}

/**
 * The organisation and the product, as structured data.
 *
 * Only on the home page. Repeating it per route does not improve anything and
 * gives a crawler several descriptions of the same entity to reconcile.
 */
export function siteJsonLd(): string {
	return JSON.stringify({
		"@context": "https://schema.org",
		"@type": "SoftwareApplication",
		name: BRAND,
		url: SITE_URL,
		image: `${SITE_URL}${OG_IMAGE_PATH}`,
		applicationCategory: "DeveloperApplication",
		operatingSystem: "Web",
		description: DEFAULT_DESCRIPTION,
		/* Free while in beta, and the page says so. A price of 0 is a claim, so
		   it has to keep matching the copy. */
		offers: {
			"@type": "Offer",
			price: "0",
			priceCurrency: "USD",
		},
	});
}
