// Generated by vitest-stats-reporter.ts on every full `pnpm test`.
// Do not edit by hand — your change will be overwritten by the next run.

export const SUITE_STATS = {
	files: 58,
	total: 1151,
	byDir: {
		src: 4,
		"src/components": 559,
		"src/lib": 475,
		"src/routes": 103,
		"src/test": 10,
	},
} as const;
