// Generated by vitest-stats-reporter.ts on every full `pnpm test`.
// Do not edit by hand — your change will be overwritten by the next run.

export const SUITE_STATS = {
	files: 14,
	total: 204,
	byDir: {
		src: 1,
		"src/components": 181,
		"src/db": 5,
		"src/lib": 17,
	},
} as const;
