import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import type { Reporter, TestModule } from "vitest/node";

/**
 * Writes the suite's own numbers back into the repo so the landing page can
 * quote them without anyone hand-syncing a constant.
 *
 * Section 06 prints how many tests and test files this repo has. That number
 * cannot be derived by reading source — `it.each` expands at runtime — so the
 * only honest source for it is a finished run. This reporter is that source.
 *
 * Deliberately conservative about when it writes: a partial or failing run
 * would produce a number that is real but not the one the page means.
 */

const OUT = "src/test/suite-stats.ts";
const IS_SPEC = /\.(test|spec)\.tsx?$/;

/** Mirrors `include` in vitest.config.ts. */
function countSpecsOnDisk(dir: string): number {
	let found = 0;
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const path = `${dir}/${entry.name}`;
		if (entry.isDirectory()) found += countSpecsOnDisk(path);
		else if (IS_SPEC.test(entry.name)) found += 1;
	}
	return found;
}

/** `src/components/landing/hero.test.tsx` → `src/components`. */
const groupOf = (file: string) => file.split("/").slice(0, 2).join("/");

const toRepoPath = (id: string) =>
	relative(process.cwd(), id).split("\\").join("/");

function render(files: number, byDir: Map<string, number>) {
	const entries = [...byDir]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([dir, tests]) => `\t\t"${dir}": ${tests},`)
		.join("\n");

	const total = [...byDir.values()].reduce((sum, n) => sum + n, 0);

	return `// Generated by vitest-stats-reporter.ts on every full \`pnpm test\`.
// Do not edit by hand — your change will be overwritten by the next run.

export const SUITE_STATS = {
	files: ${files},
	total: ${total},
	byDir: {
${entries}
	},
} as const;
`;
}

export default class StatsReporter implements Reporter {
	onTestRunEnd(
		testModules: ReadonlyArray<TestModule>,
		_errors: unknown,
		reason: string,
	) {
		if (reason !== "passed") return;

		// A filtered run (`vitest run some.test.tsx`) sees only part of the repo.
		// Publishing that as the total would understate it.
		if (testModules.length !== countSpecsOnDisk(resolve(process.cwd(), "src")))
			return;

		const byDir = new Map<string, number>();
		for (const mod of testModules) {
			const dir = groupOf(toRepoPath(mod.moduleId));
			const count = [...mod.children.allTests()].length;
			byDir.set(dir, (byDir.get(dir) ?? 0) + count);
		}

		const next = render(testModules.length, byDir);
		const path = resolve(process.cwd(), OUT);

		// Only touch the file when the numbers actually moved, so watch mode does
		// not chase its own tail.
		let current = "";
		try {
			current = readFileSync(path, "utf8");
		} catch {
			// First run — the file does not exist yet.
		}
		if (current !== next) writeFileSync(path, next);
	}
}
