import type {
	StarterAnswers,
	StarterQuestionId,
} from "@/lib/starter-questions";
import { STARTER_QUESTIONS } from "@/lib/starter-questions";
import type { StarterFiles } from "./build-starter";
import { packageManager, runScript } from "./package-manager";

/**
 * The instructions for a starter, read out of the starter itself.
 *
 * Every line here is derived from the generated files rather than written
 * alongside them: the commands come from `package.json`, the variables from
 * `.env.example`, and the steps that only apply to some stacks are decided by
 * what those files contain. A guide typed by hand would be a second source of
 * truth that starts out correct and quietly stops being — telling someone to
 * run `db:push` in a project that has no database is exactly the kind of
 * wrongness that makes a reader distrust the rest of it.
 *
 * Pure, so `guide.test.ts` can assert it against every combination the wizard
 * allows rather than against one.
 */

export type GuideCommand = {
	/** What to run, verbatim. */
	command: string;
	/** Why, in one line. */
	note?: string;
};

export type GuideVariable = {
	name: string;
	/** The comment that sits above it in `.env.example`. */
	comment: string;
	/** Compiled into the browser bundle, so never a secret. */
	isPublic: boolean;
};

export type GuideStep = {
	/** Short imperative heading — "Install", "Fill in your environment". */
	title: string;
	body: string;
	commands?: GuideCommand[];
	variables?: GuideVariable[];
};

/** Node's version is a real prerequisite, not a suggestion. */
export const NODE_VERSION = "20.9";

/**
 * Reads `.env.example` back into the variables it documents.
 *
 * The file is generated by `envExample`, so this is the inverse of a format
 * this codebase owns — a comment line, then `NAME=`, then a blank.
 */
export function parseEnvExample(contents: string): GuideVariable[] {
	const out: GuideVariable[] = [];
	const lines = contents.split("\n");

	for (const [index, line] of lines.entries()) {
		const match = /^([A-Z][A-Z0-9_]*)=/.exec(line);
		if (!match?.[1]) continue;

		/* The nearest comment above it, skipping the banner that introduces the
		   public block — that one describes the section, not the variable. */
		const previous = (lines[index - 1] ?? "").trim();
		const comment =
			previous.startsWith("#") && !previous.includes("prefix is what")
				? previous.replace(/^#\s?/, "")
				: "";

		out.push({
			name: match[1],
			comment,
			isPublic: /^(NEXT_PUBLIC_|VITE_)/.test(match[1]),
		});
	}
	return out;
}

const labelFor = (id: StarterQuestionId, answers: StarterAnswers) => {
	const question = STARTER_QUESTIONS.find((candidate) => candidate.id === id);
	return question?.options?.find((option) => option.id === answers[id])?.label;
};

/** The whole guide, in the order someone actually does it. */
export function starterGuide(
	files: StarterFiles,
	answers: StarterAnswers,
): GuideStep[] {
	const pkg = JSON.parse(files["package.json"] ?? "{}") as {
		scripts?: Record<string, string>;
	};
	const scripts = pkg.scripts ?? {};
	const variables = parseEnvExample(files[".env.example"] ?? "");
	const project = answers.project ?? "your-app";
	const manager = packageManager(answers);

	const steps: GuideStep[] = [
		{
			title: "Unpack it",
			body: `Unzip the download and open the folder. Node ${NODE_VERSION} or newer is required — the generated code uses features older versions do not have.`,
			commands: [{ command: `cd ${project}` }],
		},
		{
			title: "Install",
			body: `No lockfile ships with the starter, so this first install is what resolves the versions and writes \`${manager.lockfile}\`. Commit it.`,
			commands: [{ command: manager.install }],
		},
	];

	if (variables.length > 0) {
		steps.push({
			title: "Fill in your environment",
			body: `Copy \`.env.example\` to \`.env\` and set each value. \`src/lib/env.ts\` parses them at boot, so a missing one fails immediately with its name rather than as \`undefined\` somewhere later.`,
			commands: [{ command: "cp .env.example .env" }],
			variables,
		});
	}

	if (scripts["db:push"]) {
		steps.push({
			title: "Create the tables",
			body: `Pushes the schema in \`src/db/schema.ts\` to ${
				labelFor("database", answers) ?? "your database"
			}. Run it again whenever the schema changes.`,
			commands: [{ command: runScript(answers, "db:push") }],
		});
	}

	steps.push({
		title: "Check it before you change it",
		body: "The starter ships its own tests and passes them on a clean install. Running them first means any failure after this is yours, which is the point of shipping them.",
		commands: [
			...(scripts.test ? [{ command: runScript(answers, "test") }] : []),
			...(scripts.typecheck
				? [{ command: runScript(answers, "typecheck") }]
				: []),
		],
	});

	if (scripts.dev) {
		steps.push({
			title: "Run it",
			body: "Starts the dev server on http://localhost:3000.",
			commands: [{ command: runScript(answers, "dev") }],
		});
	}

	const rest = Object.entries(scripts).filter(
		([name]) => !["dev", "test", "typecheck", "db:push"].includes(name),
	);

	if (rest.length > 0) {
		steps.push({
			title: "Everything else it can do",
			body: "The remaining scripts, and what each is for.",
			commands: rest.map(([name, command]) => ({
				command: runScript(answers, name),
				note: command,
			})),
		});
	}

	return steps;
}

/**
 * Where to look first, for a person or a model reading the repo cold.
 *
 * Only files the starter actually contains are listed — the tour is generated
 * from the same `files` the tree is, so it cannot point at something that is
 * not in the zip.
 */
export function starterTour(
	files: StarterFiles,
): { path: string; what: string }[] {
	const candidates: { path: string; what: string }[] = [
		{ path: "README.md", what: "The stack you chose, and these steps again." },
		{
			path: "ARCHITECTURE.md",
			what: "Where things live and the two rules that keep them there.",
		},
		{
			path: "AGENTS.md",
			what: "What to tell an AI assistant before it touches the repo.",
		},
		{ path: "src/lib/env.ts", what: "Every environment variable, typed." },
		{ path: "src/lib/auth.ts", what: "Authentication, configured once." },
		{ path: "src/lib/checkout.ts", what: "Billing, configured once." },
		{
			path: "src/db/schema.ts",
			what: "The database schema. The only place SQL is written.",
		},
		{ path: "src/lib/email.ts", what: "Transactional email, configured once." },
	];

	return candidates.filter((entry) => entry.path in files);
}
