import { BRAND, LOGO_SIZE, LOGO_SRC, README_URL, REPO_URL } from "@/lib/brand";
import { SUITE_STATS } from "@/test/suite-stats";

/**
 * Section 12 — `footer`: the six-column link grid, the logo at page width, and
 * a bottom bar carrying a live-ish status dot.
 *
 * The reference's dot reads "All systems operational" off a status page. There
 * is nothing here to be operational, so it reads the suite instead — a number
 * that is regenerated by every full run and is true by construction.
 *
 * Nothing in the link grid is decorative. Anchors resolve to sections this page
 * renders, files resolve to files in the repo, and every name in the two stack
 * columns is a package `package.json` actually depends on. `footer.test.tsx`
 * checks all three.
 */

type Link = { label: string; href: string };

/** In-page anchors. Each one is an `id` some section on this page carries. */
export const PRODUCT_LINKS: Link[] = [
	{ label: "Features", href: "#features" },
	{ label: "Testing", href: "#testing" },
	{ label: "Use cases", href: "#use-cases" },
];

/**
 * The two pages a signed-up visitor is entitled to find, and the two a Google
 * OAuth review opens. Both are real routes on this site rather than links out
 * to a document behind somebody else's login, which is a common reason that
 * review comes back.
 */
export const LEGAL_LINKS: Link[] = [
	{ label: "Privacy", href: "/privacy" },
	{ label: "Terms", href: "/terms" },
];

export const REPO_LINKS: Link[] = [
	{ label: "GitHub", href: REPO_URL },
	{ label: "README", href: README_URL },
	{ label: "Issues", href: `${REPO_URL}/issues` },
];

type Dependency = Link & { pkg: string };

export const STACK_LINKS: Dependency[] = [
	{
		label: "TanStack Start",
		href: "https://tanstack.com/start",
		pkg: "@tanstack/react-start",
	},
	{
		label: "TanStack Query",
		href: "https://tanstack.com/query",
		pkg: "@tanstack/react-query",
	},
	{
		label: "Supabase",
		href: "https://supabase.com",
		pkg: "@supabase/supabase-js",
	},
];

export const TOOLING_LINKS: Dependency[] = [
	{ label: "Vite", href: "https://vite.dev", pkg: "vite" },
	{ label: "Vitest", href: "https://vitest.dev", pkg: "vitest" },
	{
		label: "Tailwind CSS",
		href: "https://tailwindcss.com",
		pkg: "tailwindcss",
	},
	{ label: "Biome", href: "https://biomejs.dev", pkg: "@biomejs/biome" },
	{
		label: "TypeScript",
		href: "https://www.typescriptlang.org",
		pkg: "typescript",
	},
];

/** Files an agent is pointed at, by path in the repo. */
export const AGENT_FILES = [".cursorrules", "README.md"];

const YEAR = new Date().getFullYear();

const isExternal = (href: string) => href.startsWith("http");

function Column({ links, title }: { links: Link[]; title: string }) {
	return (
		<div className="flex flex-col gap-3">
			<h4 className="mb-1 text-[14px] font-medium text-ink">{title}</h4>
			{links.map((link) => (
				<a
					className="text-[14px] text-ink-muted transition-colors duration-300 hover:text-ink"
					href={link.href}
					key={link.label}
					{...(isExternal(link.href)
						? { rel: "noreferrer", target: "_blank" }
						: {})}
				>
					{link.label}
				</a>
			))}
		</div>
	);
}

export function Footer() {
	return (
		<footer className="overflow-hidden border-white/10 border-t bg-base px-gutter pt-10 pb-4 md:px-6 md:pt-15 md:pb-6">
			<div className="mx-auto grid max-w-content grid-cols-2 gap-6 sm:grid-cols-3 lg:grid-cols-7">
				<Column links={PRODUCT_LINKS} title="Product" />
				<Column links={REPO_LINKS} title="Repository" />
				<Column links={STACK_LINKS} title="Stack" />
				<Column links={TOOLING_LINKS} title="Tooling" />
				<Column links={LEGAL_LINKS} title="Legal" />

				<div className="col-span-2 flex flex-col gap-3 sm:col-span-3 lg:col-span-2">
					<h4 className="mb-1 text-[14px] font-medium text-ink">
						Point your agent at it
					</h4>
					<div className="flex flex-wrap gap-2">
						{AGENT_FILES.map((file) => (
							<a
								className="inline-flex items-center gap-1.5 rounded-lg border border-white/15 px-4 py-2 font-mono text-[13px] text-white/60 transition-colors duration-200 hover:border-white/30 hover:bg-white/4 hover:text-white/90"
								href={`${REPO_URL}/blob/main/${file}`}
								key={file}
								rel="noreferrer"
								target="_blank"
							>
								{file}
							</a>
						))}
					</div>
				</div>
			</div>

			{/* The logo at page width, which is what the reference does with its own.
			    It is the navbar's mark blown up, so it carries no information the page
			    has not already given: decorative, and hidden from the reader. Sized by
			    intrinsic ratio so the box exists before the file lands.

			    It rests dimmed because at this size the full-strength orange outshouts
			    the CTA above it, and comes up to full on hover. The reveal is a hover
			    state on a decorative image, so nothing is behind it — a pointer is the
			    only thing that can ask for it, and nothing is lost by never asking. */}
			<div className="mx-auto max-w-content pt-[160px] pb-5">
				<img
					alt=""
					aria-hidden="true"
					className="block w-full select-none opacity-15 transition-opacity duration-500 ease-out hover:opacity-100"
					data-wordmark
					decoding="async"
					height={LOGO_SIZE.height}
					loading="lazy"
					src={LOGO_SRC}
					width={LOGO_SIZE.width}
				/>
			</div>

			<div className="mx-auto grid max-w-content grid-cols-1 items-center gap-3 py-4 text-[12px] text-white/40 sm:grid-cols-2">
				<p>
					© {YEAR} {BRAND}
				</p>
				<p className="flex items-center gap-1.5 sm:justify-end">
					<span
						aria-hidden="true"
						className="dot-pulse size-2 shrink-0 rounded-full bg-sage"
					/>
					{SUITE_STATS.total} tests passing on this site
				</p>
			</div>
		</footer>
	);
}
